// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_tsrm_TMBExports
#include <TMB.hpp>
#include "tsrmTMB.h"
#include "srm_tmb.hpp"
#include "srm_groups_tmb.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "srm_tmb") {
    return srm_tmb(this);
  } else if(model == "srm_groups_tmb") {
    return srm_groups_tmb(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
