// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_V_export
Eigen::MatrixXd compute_V_export(const Eigen::MatrixXd& tZg, const Eigen::MatrixXd& tZp, const Eigen::MatrixXd& tZd, const Eigen::MatrixXd& tZt, const Eigen::MatrixXd& SIGMA_G, const Eigen::MatrixXd& SIGMA_P, const Eigen::MatrixXd& SIGMA_D, const Eigen::MatrixXd& SIGMA_T);
RcppExport SEXP _tsrm_compute_V_export(SEXP tZgSEXP, SEXP tZpSEXP, SEXP tZdSEXP, SEXP tZtSEXP, SEXP SIGMA_GSEXP, SEXP SIGMA_PSEXP, SEXP SIGMA_DSEXP, SEXP SIGMA_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZg(tZgSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZp(tZpSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZd(tZdSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZt(tZtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_G(SIGMA_GSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_P(SIGMA_PSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_D(SIGMA_DSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_T(SIGMA_TSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_V_export(tZg, tZp, tZd, tZt, SIGMA_G, SIGMA_P, SIGMA_D, SIGMA_T));
    return rcpp_result_gen;
END_RCPP
}
// compute_V_sparse_export
Eigen::MatrixXd compute_V_sparse_export(const Eigen::MatrixXd& tZg, const Eigen::SparseMatrix<double>& tZp, const Eigen::SparseMatrix<double>& tZd, const Eigen::SparseMatrix<double>& tZt, const Eigen::MatrixXd& SIGMA_G, const Eigen::SparseMatrix<double>& SIGMA_P, const Eigen::SparseMatrix<double>& SIGMA_D, const Eigen::SparseMatrix<double>& SIGMA_T);
RcppExport SEXP _tsrm_compute_V_sparse_export(SEXP tZgSEXP, SEXP tZpSEXP, SEXP tZdSEXP, SEXP tZtSEXP, SEXP SIGMA_GSEXP, SEXP SIGMA_PSEXP, SEXP SIGMA_DSEXP, SEXP SIGMA_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZg(tZgSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type tZp(tZpSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type tZd(tZdSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type tZt(tZtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_G(SIGMA_GSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type SIGMA_P(SIGMA_PSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type SIGMA_D(SIGMA_DSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type SIGMA_T(SIGMA_TSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_V_sparse_export(tZg, tZp, tZd, tZt, SIGMA_G, SIGMA_P, SIGMA_D, SIGMA_T));
    return rcpp_result_gen;
END_RCPP
}
// gradient_singlegroup_export
Eigen::VectorXd gradient_singlegroup_export(const Rcpp::List& parm_list, const Eigen::MatrixXd& ty, const Eigen::MatrixXd& tX, const Eigen::MatrixXd& tZg, const Eigen::MatrixXd& tZp, const Eigen::MatrixXd& tZd, const Eigen::MatrixXd& tZt, const Eigen::MatrixXd& SIGMA_G, const Eigen::MatrixXd& SIGMA_P, const Eigen::MatrixXd& SIGMA_D, const Eigen::MatrixXd& SIGMA_T, const Eigen::VectorXd& BETA, int np, int nd, int nt, const Eigen::MatrixXi& parm_mat, bool with_reml, const std::string& model);
RcppExport SEXP _tsrm_gradient_singlegroup_export(SEXP parm_listSEXP, SEXP tySEXP, SEXP tXSEXP, SEXP tZgSEXP, SEXP tZpSEXP, SEXP tZdSEXP, SEXP tZtSEXP, SEXP SIGMA_GSEXP, SEXP SIGMA_PSEXP, SEXP SIGMA_DSEXP, SEXP SIGMA_TSEXP, SEXP BETASEXP, SEXP npSEXP, SEXP ndSEXP, SEXP ntSEXP, SEXP parm_matSEXP, SEXP with_remlSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parm_list(parm_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type ty(tySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tX(tXSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZg(tZgSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZp(tZpSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZd(tZdSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZt(tZtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_G(SIGMA_GSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_P(SIGMA_PSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_D(SIGMA_DSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_T(SIGMA_TSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type BETA(BETASEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type parm_mat(parm_matSEXP);
    Rcpp::traits::input_parameter< bool >::type with_reml(with_remlSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_singlegroup_export(parm_list, ty, tX, tZg, tZp, tZd, tZt, SIGMA_G, SIGMA_P, SIGMA_D, SIGMA_T, BETA, np, nd, nt, parm_mat, with_reml, model));
    return rcpp_result_gen;
END_RCPP
}
// gradient_singlegroup_sparse_export
Eigen::VectorXd gradient_singlegroup_sparse_export(const Rcpp::List& parm_list, const Eigen::MatrixXd& ty, const Eigen::MatrixXd& tX, const Eigen::MatrixXd& tZg, const Eigen::SparseMatrix<double>& tZp, const Eigen::SparseMatrix<double>& tZd, const Eigen::SparseMatrix<double>& tZt, const Eigen::MatrixXd& SIGMA_G, const Eigen::SparseMatrix<double>& SIGMA_P, const Eigen::SparseMatrix<double>& SIGMA_D, const Eigen::SparseMatrix<double>& SIGMA_T, const Eigen::VectorXd& BETA, int np, int nd, int nt, const Eigen::MatrixXi& parm_mat, bool with_reml, const std::string& model);
RcppExport SEXP _tsrm_gradient_singlegroup_sparse_export(SEXP parm_listSEXP, SEXP tySEXP, SEXP tXSEXP, SEXP tZgSEXP, SEXP tZpSEXP, SEXP tZdSEXP, SEXP tZtSEXP, SEXP SIGMA_GSEXP, SEXP SIGMA_PSEXP, SEXP SIGMA_DSEXP, SEXP SIGMA_TSEXP, SEXP BETASEXP, SEXP npSEXP, SEXP ndSEXP, SEXP ntSEXP, SEXP parm_matSEXP, SEXP with_remlSEXP, SEXP modelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type parm_list(parm_listSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type ty(tySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tX(tXSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type tZg(tZgSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type tZp(tZpSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type tZd(tZdSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type tZt(tZtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type SIGMA_G(SIGMA_GSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type SIGMA_P(SIGMA_PSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type SIGMA_D(SIGMA_DSEXP);
    Rcpp::traits::input_parameter< const Eigen::SparseMatrix<double>& >::type SIGMA_T(SIGMA_TSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type BETA(BETASEXP);
    Rcpp::traits::input_parameter< int >::type np(npSEXP);
    Rcpp::traits::input_parameter< int >::type nd(ndSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type parm_mat(parm_matSEXP);
    Rcpp::traits::input_parameter< bool >::type with_reml(with_remlSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type model(modelSEXP);
    rcpp_result_gen = Rcpp::wrap(gradient_singlegroup_sparse_export(parm_list, ty, tX, tZg, tZp, tZd, tZt, SIGMA_G, SIGMA_P, SIGMA_D, SIGMA_T, BETA, np, nd, nt, parm_mat, with_reml, model));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tsrm_compute_V_export", (DL_FUNC) &_tsrm_compute_V_export, 8},
    {"_tsrm_compute_V_sparse_export", (DL_FUNC) &_tsrm_compute_V_sparse_export, 8},
    {"_tsrm_gradient_singlegroup_export", (DL_FUNC) &_tsrm_gradient_singlegroup_export, 18},
    {"_tsrm_gradient_singlegroup_sparse_export", (DL_FUNC) &_tsrm_gradient_singlegroup_sparse_export, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsrm(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
